"""empty message

Revision ID: 560b4a060041
Revises: e7a3773f9cd2
Create Date: 2024-09-08 03:32:11.013397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560b4a060041'
down_revision = 'e7a3773f9cd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accelerometer', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('flex_sensor', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('sign_parameters', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.create_unique_constraint(None, ['sign'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sign_parameters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('flex_sensor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('accelerometer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
